title: The journey of my programming
author: Daniel Lukacs
email: lukacs.daniel97@protonmail.com
description: > This is the story of my programming journey.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
